### ISSUE TITLE
Not able to encode/decode streams with changing resolution

### ISSUE THREAD

**Issue by gpalsingh** [gpalsingh/mesa#3]
Example video ftp://ftp.bbc.co.uk/incoming/bbb-avc3-rep2-rep4.mp4

**Comment by CapOM** [comment]
Could be several pbs here but I believe at least one pb should be fixed by https://github.com/CapOM/gst-omx/commit/3e639177fd0032a035edc0a6bfd673cdeac494b1

**Comment by gpalsingh** [comment]
The execution hangs after a in case of both encoder and decoder. Probably my testing env has been corrupted since I've been getting frequent crashes with gst-launch lately. I'll check again after the reinstall.

**Comment by gpalsingh** [comment]
Cleaned everything and tried again. Still same results.

**Comment by CapOM** [comment]
I started to look at it and I fixed a few bits, please merge the 2 last commits named

h264dprc.c: reset slice pointer on resolution change (this fixes a crash)
h264dprc.c: properly parse frame width and height 

from https://github.com/CapOM/mesa/commits/gsoc-dev
Thx!

**Comment by gpalsingh** [comment]
Hi,

I tested the dec after applying the patches but the window looks wrong.
![screen_output](https://user-images.githubusercontent.com/12171804/29288492-908e778a-8156-11e7-91ab-c797dbb38b31.png)
I tried it with other videos and they run normally.

Also I get a crash in the middle of the video
```
Thread 22 "video" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdeb9f700 (LWP 10678)]
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:39
39	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:39
#1  0x00007fffddb615e0 in util_copy_rect (dst=0x7fffb41dffb0 "\213\201\213\201\213\201\213\201\213\202\213\202\213\202\213\202", format=PIPE_FORMAT_R8G8_UNORM, dst_stride=1920, dst_x=0, dst_y=0, width=960, height=135, src=0x7fffde55d000 <error: Cannot access memory at address 0x7fffde55d000>, src_stride=1024, src_x=0, src_y=0) at util/u_surface.c:105
#2  0x00007fffddaf0c4a in h264d_fill_output (p_prc=0x7ffff7f11010, buf=0x7fffd8108670, output=0x7fffd80f4c90) at h264dprc.c:1450
#3  0x00007fffddaf0f30 in h264d_frame_decoded (p_prc=0x7ffff7f11010, input=0x7fffd80f4860, output=0x7fffd80f4c90) at h264dprc.c:1502
#4  0x00007fffddaf1016 in h264d_manage_buffers (p_prc=0x7ffff7f11010) at h264dprc.c:1517
#5  0x00007fffddaf1329 in decode_frame (p_prc=0x7ffff7f11010, in_buf=0x7fffd80f48f0) at h264dprc.c:1574
#6  0x00007fffddaf1a26 in h264d_prc_buffers_ready (ap_obj=0x7ffff7f11010) at h264dprc.c:1729
#7  0x00007fffe488011b in prc_dispatch_msg (ap_obj=0x7ffff7f11010, ap_msg=0x7fffd8002248) at tizprc.c:654
#8  0x00007fffe485f925 in srv_tick (ap_obj=0x7ffff7f11010) at tizservant.c:234
#9  0x00007fffe4852a6f in schedule_servants (ap_state=<optimized out>, ap_sched=0x7fffe0005730) at tizscheduler.c:2374
#10 il_sched_thread_func (p_arg=0x7fffe0005730) at tizscheduler.c:2422
#11 0x00007ffff72f76ba in start_thread (arg=0x7fffdeb9f700) at pthread_create.c:333
#12 0x00007ffff702d3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

I use this branch after applying my changes over the patches you provided https://github.com/gpalsingh/mesa/commits/gsoc-dev

Thanks

**Comment by CapOM** [comment]
Yes it is not finished yet. (the reason why the windows looks wrong is a bug in gs th264parse element which says it is 1280x720). Without the 2 patches I mentioned it should be same window pb . I do not see the 2 commits in your branch.

**Comment by gpalsingh** [comment]
That might be because I applied them not on the top of the branch but after https://github.com/gpalsingh/mesa/commit/eee6d9ff2b545f1d6ea7daded013fe37754d1d3b and before https://github.com/gpalsingh/mesa/commit/305251f6b1609dea1dd92481bcda226a4bfa2234
